def log_empty(): print(' > 🗑️  ( empty equities universe ) - [ size : 0 ]')
def log_auto():  print(' > 🦀 ( autobuilder started )')
def log_full(size):  print(' > 🐋 ( equities universe ) - [ size : %s ]'%size)
def log_download(): print(' > 📦 ( downloading sec packages )\t')
def log_parse(): print(' > ✨ ( parsing data structs )\t')
def log_built(): print(' > 🏭 ( local storage built )\t')
def log_purge(): print(' > 💀 ( equities universe purged ) - [local storage deleted]\t')